on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: janithcooray/wrangler-action@v1.0.1
        with:
          apiToken: ${{ secrets.PAGES_DEPLOY_API }}
          accountId: ${{ secrets.PAGES_DEPLOY_ACCOUNT }}
          workingDirectory: 'test'
          pagesDirectory: 'public'
          pagesProject: 'cloud-functions'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
